from typing import Any
from blog.models import post,Category
from django.core.management.base import BaseCommand
import random



class Command(BaseCommand):
    help ="this command insert data"


    def handle(self,*args:Any, **options:Any) :
        post.objects.all().delete()
    

    # delete existing data

        
        titles =[
              "One Piece",
              "Demon Slayer",
              "Naruto",
              "Bleach",
              "Haikyu",
              "Attack on Titan",
             "Chainsaw Man",
            "Jujutsu Kaisen",
              "Black Clover",
             "Buruto:Naruto Next Generation",
              "Solo Leveling",
              "Blue Lock",
              "Dragon Ball Z",
              "Death Note",
              "Tokyo Revengers",
              "One Punch Man",
              "Overload",
             "Ninja Kamul",
             "Dr.Stone",
              "Baki",
            ]
          
        contents =[
                "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece. [Written by MAL Rewrite] ",
               
                "Demon Slayer: Kimetsu no Yaiba (鬼滅の刃, Kimetsu no Yaiba, rgh. Blade of Demon Destruction is a Japanese manga series written and illustrated by Koyoharu Gotouge. It was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from February 2016 to May 2020, with its chapters collected in 23 tankōbon volumes. It has been published in English by Viz Media and simultaneously on the Manga Plus platform by Shueisha. It follows teenage Tanjiro Kamado, who strives to become a Demon Slayer after his family was slaughtered and his younger sister, Nezuko, is turned into a demonA 26-episode anime television series adaptation produced by Ufotable aired from April to September 2019, with a sequel film, Demon Slayer: Kimetsu no Yaiba The Movie: Mugen Train, released in October 2020 and became the highest-grossing anime film and Japanese film of all time. An 18-episode second season of the anime series aired from October 2021 to February 2022 while a compilation film, Demon Slayer: Kimetsu no Yaiba To the Swordsmith Village, was released in February 2023. An 11-episode third season aired from April to June 2023 while another compilation film, Demon Slayer: Kimetsu no Yaiba To the Hashira Training, was released in February 2024. A fourth season premiered in May 2024.",
    
                "Naruto is a Japanese manga series written and illustrated by Masashi Kishimoto. It tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts: the first is set in Naruto's pre-teen years (volumes 1,27), and the second in his teens (volumes 28,72). The series is based on two one-shot manga by Kishimoto: Karakuri (1995), which earned Kishimoto an honorable mention in Shueisha's monthly Hop Step Award the following year, and Naruto (1997).Naruto was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from September 1999 to November 2014, with its chapters collected in 72 tankōbon volumes. Viz Media licensed the manga for North American production and serialized Naruto in their digital Weekly Shonen Jump magazine. Part I of the manga was adapted into an anime television series by Pierrot and Aniplex, which ran for 220 episodes from October 2002 to February 2007 on TV Tokyo. A second series, which adapts material from Part II of the manga, is titled Naruto: Shippuden and ran on TV Tokyo for 500 episodes from February 2007 to March 2017. Pierrot also developed 11 animated films and 12 original video animations (OVAs). The franchise includes light novels, video games, and trading cards developed by several companies. The story of Naruto continues in Boruto, where Naruto's son Boruto Uzumaki creates his own ninja way instead of following his father's.",

                "Bleach (stylized in all caps) is a Japanese anime television series based on Tite Kubo's original manga series of the same name. It was produced by Studio Pierrot and directed by Noriyuki Abe. The series aired on TV Tokyo from October 2004 to March 2012, spanning 366 episodes. The story follows the adventures of Ichigo Kurosaki after he obtains the powers of a Soul Reaper—a death personification similar to the Grim Reaper—from another Soul Reaper, Rukia Kuchiki. His newfound powers force him to take on the duties of defending humans from evil spirits and guiding departed souls to the afterlife. In addition to adapting the manga series it is based on, the anime periodically includes original self-contained storylines and characters not found in the source material.Viz Media obtained foreign television and home video distribution rights to the Bleach anime in March 2006. Bleach was broadcast in the United States on Adult Swim from September 2006 to November 2014.",               
         
                "Haikyu!! (ハイキュー!!, Haikyū!!, from the kanji 排球 volleyball) is a Japanese manga series written and illustrated by Haruichi Furudate. It was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from February 2012 to July 2020, with its chapters collected in 45 tankōbon volumes. The story follows Shoyo Hinata, a boy determined to become a great volleyball player despite his small stature.An anime television series adaptation produced by Production I.G, aired on MBS from April to September 2014, with 25 episodes. A second season aired from October 2015 to March 2016, with 25 episodes. A third season aired from October to December 2016, with 10 episodes. A fourth season was released in two split cours from January to December 2020, with 25 episodes. The anime film series titled Haikyu!! Final will be released in two parts, which serves as the finale of the series; the first was released in February 2024.",
                
                "Attack on Titan (Japanese: 進撃の巨人, Hepburn: Shingeki no Kyojin,The Advancing Giant') is a Japanese dark fantasy anime television series, adapted from the manga series of the same name by Hajime Isayama. The series premiered on April 7, 2013, and concluded on November 5, 2023. It has aired on MBS TV (first two seasons) and NHK General TV (third season onwards). In North America, the series has been streamed on Crunchyroll, Funimation and Hulu. Attack on Titan has also aired on Adult Swim's Toonami programming block in the United States.Set in a post-apocalyptic world where the remains of humanity live behind walls protecting them from giant humanoid Titans, Attack on Titan follows protagonist Eren Yeager, along with friends Mikasa Ackerman and Armin Arlert. When a Colossal Titan breaches the wall of their hometown, Titans destroy the city and eat Erens mother. Vowing vengeance, Eren joins the elite Survey Corps, a group of soldiers who fight against Titans. It chronicles Erens journey with the Survey Corps as they fight against the Titans while investigating their origin and history.",
         
                "Chainsaw Man (Japanese: チェンソーマン, Hepburn: Chensō Man) is a Japanese manga series written and illustrated by Tatsuki Fujimoto. Its first arc was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from December 2018 to December 2020; its second arc began serialization in Shueisha's Shōnen Jump+ app and website in July 2022. Its chapters have been collected in 17 tankōbon volumes as of April 2024.Chainsaw Man follows the story of Denji, an impoverished teenager who makes a contract that fuses his body with that of a dog-like Devil named Pochita, granting him the ability to transform parts of his body into chainsaws. Denji eventually joins the Public Safety Devil Hunters, a government agency focused on fighting against Devils whenever they become a threat to Japan. The second arc of the story focuses on Asa Mitaka, a high school student who enters into a contract with Yoru, the War Devil, who forces her to hunt down Chainsaw Man in order to reclaim what he had stolen from her.",

                "Jujutsu Kaisen (呪術廻戦, rgh. Sorcery Battle) is a Japanese manga series written and illustrated by Gege Akutami. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since March 2018, with its chapters collected in 26 tankōbon volumes as of April 2024. The story follows high school student Yuji Itadori as he joins a secret organization of Jujutsu Sorcerers to eliminate a powerful Curse named Ryomen Sukuna, of whom Yuji becomes the host. Jujutsu Kaisen is a sequel to Akutami's Tokyo Metropolitan Curse Technical School, serialized in Shueisha's Jump Giga from April to July 2017, later collected in a tankōbon volume, retroactively titled as Jujutsu Kaisen 0, in December 2018.Jujutsu Kaisen is licensed for English-language release in North America by Viz Media, which has published the manga in print since December 2019. Shueisha publishes the series in English on the Manga Plus online platform. Two novels, written by Ballad Kitaguni, were published in May 2019 and January 2020, respectively. A 24-episode anime television series adaptation produced by MAPPA, aired on MBS from October 2020 to March 2021; a second season aired from July to December 2023. A sequel covering the culling Game arc has been announced. The anime is licensed by Crunchyroll for streaming outside of Asia, which premiered an English dub in November 2020. The anime's original soundtrack was released in April 2021.",
                 
                "Black Clover (Japanese: ブラッククローバー, Hepburn: Burakku Kurōbā) is a Japanese manga series written and illustrated by Yūki Tabata. It started in Shueisha's shōnen manga magazine Weekly Shōnen Jump in February 2015. The series ran in the magazine until August 2023, and moved to Jump Giga in December of the same year. Its chapters have been collected in 36 tankōbon volumes as of February 2024. Set in a world where everyone is given the ability to use magic, the story follows Asta, a young boy born without any magic power who is given a rare grimoire that grants him anti-magic abilities. With his fellow mages from the Black Bulls, Asta plans to become the next Wizard King.The manga was first adapted into an original video animation (OVA) by Xebec Zwei, released in 2017. A 170-episode anime television series adaptation produced by Pierrot aired on TV Tokyo from October 2017 to March 2021. An anime film, titled Black Clover: Sword of the Wizard King, premiered simultaneously in Japanese theaters and internationally on Netflix in June 2023.In North America, the manga is licensed for English release by Viz Media, while the anime series is licensed by Crunchyroll.", 
                 
                "Boruto is a Japanese manga series written by Ukyō Kodachi and Masashi Kishimoto, and illustrated by Mikio Ikemoto. It initially began monthly serialization under the title Boruto: Naruto Next Generations,[b] with Kodachi as writer and Kishimoto as editorial supervisor in Shueisha's shōnen manga magazine Weekly Shōnen Jump in May 2016, and was transferred to Shueisha's monthly magazine V Jump in July 2019. In November 2020, Kodachi stepped down, with Kishimoto taking over as writer. In April 2023, the series concluded the first part of the story and, following a brief hiatus, continued in August of the same year with a second part titled Boruto: Two Blue Vortex.[c] Boruto is a spin-off and a sequel to Kishimoto's Naruto and follows the exploits of Naruto Uzumaki's son, Boruto Uzumaki, and his ninja team.Boruto originated from Shueisha's proposal to Kishimoto on making a sequel to Naruto. However, Kishimoto rejected this offer and proposed his former assistant Mikio Ikemoto to draw it; the writer of the film Boruto: Naruto the Movie, Ukyō Kodachi, created the plot. A 293-episode anime television series adaptation, produced by Pierrot with Ukyō Kodachi's story supervision (episodes 1–216), was broadcast on TV Tokyo from April 2017 to March 2023; a second part has been announced to be in development. Unlike the manga, which began as a retelling of the Boruto film, the anime begins as a prequel set before Boruto and his friends become ninjas in a later story arc. A series of light novels have also been written.", 
                 
                "Solo Leveling, also alternatively translated as Only 1 Level Up (Korean: 나 혼자만 레벨업; RR: Na Honjaman Rebeleop), is a South Korean web novel written by Chugong. It was serialized in Kakao's digital comic and fiction platform KakaoPage beginning on July 25, 2016, and was later published by D&C Media under their Papyrus label since November 4, 2016. The novel has been licensed in English by Yen Press.[1]A webtoon adaptation of Solo Leveling was first serialized in KakaoPage on March 4, 2018; it was illustrated by Jang Sung-rak (Dubu). The webtoon's first season concluded on March 19, 2020, and its second season was released from August 2020 to December 2021. Its individual chapters have been collected and published by D&C Media in eleven volumes as of June 2024.[2] The webtoon has been licensed in English by Yen Press.[3]", 
                 
                "Blue Lock (Japanese: ブルーロック, Hepburn: Burū Rokku) (stylized as BLUELOCK) is a Japanese manga series written by Muneyuki Kaneshiro and illustrated by Yusuke Nomura. It has been serialized in Kodansha's Weekly Shōnen Magazine since August 2018, with its chapters collected in 29 tankōbon volumes as of May 2024.An anime television series adaptation produced by Eight Bit aired from October 2022 to March 2023. An anime film adaptation based on the Episode Nagi manga premiered in April 2024. A second season is set to premiere in October 2024.By November 2023, the manga had over 30 million copies in circulation, making it one of the best-selling manga series of all time. In 2021, Blue Lock won the 45th Kodansha Manga Award in the shōnen category.", 

                "Dragon Ball (Japanese: ドラゴンボール, Hepburn: Doragon Bōru) is a Japanese media franchise created by Akira Toriyama in 1984. The initial manga, written and illustrated by Toriyama, was serialized in Weekly Shōnen Jump from 1984 to 1995, with the 519 individual chapters collected in 42 tankōbon volumes by its publisher Shueisha. Dragon Ball was originally inspired by the classical 16th-century Chinese novel Journey to the West, combined with elements of Hong Kong martial arts films. Dragon Ball characters also use a variety of East Asian martial arts styles, including karate[1][2][3] and Wing Chun (kung fu).[2][3][4] The series follows the adventures of protagonist Son Goku from his childhood through adulthood as he trains in martial arts. He spends his childhood far from civilization until he meets a teen girl named Bulma, who encourages him to join her quest in exploring the world in search of the seven orbs known as the Dragon Balls, which summon a wish-granting dragon when gathered. Along his journey, Goku makes several other friends, becomes a family man, discovers his alien heritage, and battles a wide variety of villains, many of whom also seek the Dragon Balls.Toriyama's manga was adapted and divided into two anime series produced by Toei Animation: Dragon Ball and Dragon Ball Z, which together were broadcast in Japan from 1986 to 1996. Additionally, the studio has developed 21 animated feature films and three television specials, as well as an anime sequel series titled Dragon Ball GT (1996–1997) and an anime midquel series titled Dragon Ball Super (2015–2018). From 2009 to 2015, a revised version of Dragon Ball Z aired in Japan under the title Dragon Ball Kai, as a recut that follows the manga's story more faithfully by removing most of the material featured exclusively in the anime. Several companies have developed various types of merchandise based on the series leading to a large media franchise that includes films (both animated and live-action), collectible trading card games, action figures, collections of soundtracks, and numerous video games. Dragon Ball has become one of the highest-grossing media franchises of all time.", 
                 
                "Death Note (stylized in all caps) is a Japanese manga series written by Tsugumi Ohba and illustrated by Takeshi Obata. It was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from December 2003 to May 2006, with its chapters collected in 12 tankōbon volumes. The story follows Light Yagami, a genius high school student who discovers a mysterious notebook: the Death Note, which belonged to the shinigami Ryuk, and grants the user the supernatural ability to kill anyone whose name is written in its pages. The series centers around Light's subsequent attempts to use the Death Note to carry out a worldwide massacre of individuals whom he deems immoral and to create a crime-free society, using the alias of a god-like vigilante named Kira, and the subsequent efforts of an elite Japanese police task force, led by enigmatic detective L, to apprehend him.A 37-episode anime television series adaptation, produced by Madhouse and directed by Tetsurō Araki, was broadcast on Nippon Television from October 2006 to June 2007. A light novel based on the series, written by Nisio Isin, was also released in 2006. Additionally, various video games have been published by Konami for the Nintendo DS. The series was adapted into three live-action films released in Japan in June, November 2006, and February 2008, and a television drama in 2015. A miniseries titled Death Note: New Generation and a fourth film were released in 2016. An American film adaptation was released exclusively on Netflix in August 2017, and a series is reportedly in the works.", 
                 
                "Tokyo Revengers (Japanese: 東京卍リベンジャーズ[a], Hepburn: Tōkyō Ribenjāzu) is a Japanese manga series written and illustrated by Ken Wakui. It was serialized in Kodansha's shōnen manga magazine Weekly Shōnen Magazine from March 2017 to November 2022, with its chapters collected in 31 tankōbon volumes. The story follows Takemichi Hanagaki, a 26-year-old temp worker with a gloomy life, who learns that his ex-girlfriend, Hinata Tachibana, has died in a dispute involving the Tokyo Manji Gang. The next day, while returning from a part-time job, Takemichi gets pushed off the subway platform by someone. As he is about to be hit, he jumps twelve years back in time, to the year he was dating Hinata. Finding that out, he makes the decision to do everything to prevent her death.An anime television series adaptation produced by Liden Films, aired from April to September 2021. A second season aired from January to April 2023. A third season premiered in October 2023. A live-action film adaptation was released in Japan in July 2021, with its two-part sequel released in April and June 2023.By December 2022, the manga had over 70 million copies in circulation, making it one of the best-selling manga series of all time. In 2020, Tokyo Revengers won the 44th Kodansha Manga Award for the shōnen category.", 

                "One-Punch Man (Japanese: ワンパンマン, Hepburn: Wanpanman) is a Japanese superhero manga series created by One. It tells the story of Saitama, a superhero who, because he can defeat any opponent with a single punch, grows bored from a lack of challenge. One wrote the original webcomic manga version in early 2009.A digital manga remake, illustrated by Yusuke Murata, began publication on Shueishas Tonari no Young Jump website in June 2012. Its chapters are periodically compiled and published into individual tankōbon volumes. As of March 2024, 30 volumes have been released. In North America, Viz Media licensed the remake manga for English language release and has serialized it in its Weekly Shonen Jump digital magazine.An anime adaptation produced by Madhouse was broadcast in Japan from October to December 2015. A second season, produced by J.C.Staff, was broadcast from April to July 2019. A third season also by J.C.Staff has been announced. Licensed in North America by Viz Media, it premiered in the United States on Adult Swims Toonami programming block in July 2016. The second season premiered on the block in October 2019.",  

                "Overlord (Japanese: オーバーロード, Hepburn: Ōbārōdo) is a Japanese light novel series written by Kugane Maruyama and illustrated by so-bin. It began serialization online in 2010, before being acquired by Enterbrain. Sixteen volumes have been published since July 2012. A manga adaptation by Satoshi Ōshio, with art by Hugin Miyama, began serialization in Kadokawa Shoten's manga magazine Comp Ace from November 26, 2014. Both the light novels and the manga are licensed in North America by Yen Press since 2016.The novel has been adapted into an anime television series adaptation by Madhouse, consisting of four seasons with thirteen episodes each, with the first season airing from July to September 2015. Two compilation anime films recapping the events from the first season were released in Japan in February and March 2017, respectively. The second season ran from January to April 2018, the third season ran from July to October 2018, and the fourth season ran from July to September 2022. An anime film has been announced.",

                "Ninja Kamui (stylized in all caps) is an original anime television series produced by E&H Production and Sola Entertainment with executive production by Williams Street. The series aired from February to May 2024 in the United States on Adult Swim's Toonami programming block and in Canada on Adult Swim Canada. After escaping his clan and going into hiding in rural America, former ninja Higan, living under the alias of Joe Logan is ambushed by assassins who exact bloody retribution on him and his family for his betrayal. With his wife and son now dead, Higan returns to his ninja ways to avenge his murdered family and sets his sights on taking down the very clan that made him.",

                "Dr. Stone (stylized as Dr.STONE) is a Japanese manga series written by Riichiro Inagaki and illustrated by the South Korean artist Boichi. It was serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump from March 2017 to March 2022, with its chapters collected in 27 tankōbon volumes. The story follows Senku Ishigami, a scientific genius who plans to rebuild civilization after humanity was mysteriously petrified for 3,700 years.In North America, the manga was licensed by Viz Media. Shueisha began to simulpublish the series in English on the website and app Manga Plus in January 2019. An anime television series adaptation produced by TMS Entertainment aired on Tokyo MX from July to December 2019. A second season, titled Dr. Stone: Stone Wars, aired from January to March 2021. A television special that takes place between the second and third seasons, titled Dr. Stone: Ryusui, aired in July 2022. A third season, titled Dr. Stone: New World, aired for two split cours; the first one from April to June 2023, and the second from October to December 2023. A fourth and final season, titled Dr. Stone: Science Future, has been announced.",
 
                "Baki the Grappler (Japanese: グラップラー刃牙, Hepburn: Gurappurā Baki) is a Japanese manga series written and illustrated by Keisuke Itagaki. It was originally serialized in the shōnen manga magazine Weekly Shōnen Champion from 1991 to 1999 and collected into 42 tankōbon volumes by Akita Shoten. The story follows teenager Baki Hanma as he trains and tests his fighting skills against a variety of different opponents in deadly, no rules hand-to-hand combat.The series was followed by five sequels in the same magazine; Baki (バキ, officially romanized as New Grappler Baki: In Search of Our Strongest Hero), which was serialized from 1999 to 2005 and collected into 31 volumes, Baki Hanma (範馬刃牙, Hanma Baki, officially romanized as Baki: Son of Ogre), which was serialized from 2005 to 2012 and collected into 37 volumes, Baki-Dou (刃牙道, Baki Dō, lit. Bakis Style), which was serialized from 2014 to 2018 and collected into 22 volumes, a fifth series, also named Bakidou (バキ道) but with Baki's name written in katakana instead of kanji, serialized from 2018 to 2023 and collected into 17 volumes, and Baki Rahen (刃牙らへん, Baki Rahen, lit. Baki and Others), serialized from 2023.",
                 ]
          
        img_urls =[
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReoVJuaN_6AqHkq1tMNH3VLQI0priS1kqK_w&s/id/1/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWX8-rEXWuNFa-JaWEobDuDXYkjQUux9wL2g&s/id/2/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMBO1t-2JV6y4U22IAlFGmzXqD1pt7W2X5SA&s/id/3/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0-VltHGKKZPgNRoCBOMwB-3pb8I-CVZ6BEQ&s/id/4/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDBjMcE_qwJW_YAqbLST1cTLitP_9MQmV27Q&s/id/5/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbLEJ-QXAux_144LgxsHM20JvDRXDZbUTszg&s/id/6/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqpkriiOhOaDrG8E8vCiYxjDgnVEp4jJmiZA&s/id/7/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6XTmez8lHSwRYbi7NhMHJ5O8aUaRt-qY2Xg&s/id/8/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSgfmOiB1R4t_Ks2K5lakHvgGZiQoGJg3-lg&s/id/9/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCWGOAQgUB7EJUWkENK9mD7P971qNQtdHd8w&s/id/10/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4edU0qqqkNKd4bIZqgc3OjZw2WobLakKmFA&s/id/11/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5VSrxa0rGWdGgxtV_oMLngpS3EVb1_dDabw&s/id/12/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4TXdTP2qCeGzHEk4l7nbhhjDrJRGKjZRVlg&s/id/20/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3HujS36yB0HjvJ28e1arvGB44Md78TzEngg&s/id/13/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLdScRlgzGqQ2YVAzOoUwbswvi-J_sVRMxxQ&s/id/14/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_r2x2ZOaoDRS1i_iGzmn1y3Z0F-2PK6wffg&s/id/15/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCwIKg6jkUAsW-VZkG0lCm1CH1So7oYYccLq-lkdYlxOq9Yq0p6sQoScga6XsYorma-g0&usqp=CAU/id/16/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOCeD4LruodhBET6ST9x8X8oVOYaxSshUU4A&s/id/17/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPm2m5uSvCzDhYEH6CPu_1wpHABa9oOmWvlg&s/id/18/800/400",
                 "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSASf4wWQheG-5KshrziI3wqkoeEBYtN-LWOQ&s/id/19/800/400",
                 

             ]
                 
        categories = Category.objects.all()
        for title,content,img_url in zip(titles,contents,img_urls):   
            category =random.choice(categories)         
            post.objects.create(title=title, content=content, img_url=img_url, category=category )

        self.stdout.write(self.style.SUCCESS("compeleted inserting"))    
